{% set version = "1.0-0.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-perm
  version: {{ version|replace("-", "_") }}

source:
  fn: perm_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/perm_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/perm/perm_{{ version }}.tar.gz

  sha256: 729294987bb0f367c67c4bf4071464e097ec9a2bbdb2c63f19ebfb907c604aa0

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: coin
requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('perm')"  # [not win]
    - "\"%R%\" -e \"library('perm')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=perm
  license: GPL
  summary: Perform Exact or Asymptotic permutation tests
  license_family: GPL

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
