travis:
  secure:
    BINSTAR_TOKEN: qj3ba3IsWVAo+xQ/QsMriXXhknX/OCdbtNYdD8VAFUaRvOxPcJA4eTdQK07sDTvs7YDF3hV8H/XLdmpy1numNQwCRD3aC86a9N2oD8V7eK5jjuA41KGdzzU4jdlINoVANOcDJumHMNaNNZtsaJwHAqb4XKVNyjEvc9Eb9T86RHG2TmpcioWCwFXvM29VKVu2iE/13Wgnurz3innGbabKdKAWaJOrt8qy5mxtk0sJuZwzYPDDU4mCaPcFz4VIFd7Zz+HKZ2wUv7OlH6emcuOdLFnWJ8hVZxTMwVxk2Bnkr44GxxY9XeoQQi08etnIbjvSKYzgpuspsswrQJjGiIe4+C5si4xAOqZb3WXdBai9hgDEqkAXDEF61m0zPTCRF06JR2LzCkYTxJJuyii86cfxt5a3TV9/Im4gkxK9+Fr2UfkdPEH15mEirjGADM8LBDNu/D/CpkL2V3du8rPoNnJybIYcL2FNZMx//7ApHmXyxLCy2xC2rOjMJZP/SDsqEMhiXN0kXpS53svSOPolRFn9Y5wVyuwacltuFZbd1qKUFTFHnOJ8/hQYfM9KBFTw0DcT7JOuM/9wCipjlbLPXvT1HcWigrfv+8biVatMY8M3UxrrarEkKSL1RaAjoCzfry0L3CN5BkwXQ+cgOkDANNOfinydEYGOHQCOzX4Qt7HXDzY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
